# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.cache/wt [current_project]
set_property parent.project_path C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/package_dsed.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/FSMD_microphone.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/RAM.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/address_manager.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/and_2_not.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/audio_interface.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/ca2.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/controlador_filtro.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/en_4_cycles.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/fir_data_flow.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/fir_filter.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/hold.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/multiplexor.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/multiplexor_1.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/multiplexor_2.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/multiplicador.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/mux_0_1.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/or_2.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/pwm.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/refresco.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/registro.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/seconds_calculator.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/seconds_display.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/sumador.vhd
  C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/new/dsed_audio.vhd
}
read_ip -quiet C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/clk_12M/clk_12M.xci
set_property used_in_implementation false [get_files -all c:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/clk_12M/clk_12M_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/clk_12M/clk_12M.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/clk_12M/clk_12M_ooc.xdc]
set_property is_locked true [get_files C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/clk_12M/clk_12M.xci]

read_ip -quiet C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/Jorge/Documents/VHDL/final_dsed/final_dsed.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jorge/Documents/VHDL/final_dsed/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Jorge/Documents/VHDL/final_dsed/Nexys4DDR_Master.xdc]


synth_design -top dsed_audio -part xc7a100tcsg324-1 -retiming


write_checkpoint -force -noxdef dsed_audio.dcp

catch { report_utilization -file dsed_audio_utilization_synth.rpt -pb dsed_audio_utilization_synth.pb }
